---
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.10.3
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Analyzing the Oakland license plates

```{python}
# Data frame library.
import pandas as pd
# Library for plotting maps.
import folium
```

See [background](background.Rmd) for the background to this notebook, and [clean plates](clean_plates.Rmd) for the simple cleaning we did to the raw data.


## The data


We load the cleaned license plate data from the file we saved earlier.


```{python}
# Load all license plate data.
# This may take about 30 seconds, depending on your machine.
lprs = pd.read_csv('all_lprs.csv.gz')
lprs
```

Notice that we have about 2.7 million license plate reads.

Let's start by seeing what can be learned about someone, using
this data — assuming you know their license plate


## Searching for the Fire Chief


You can imagine various ways we could get someone's license
plate, but here is an easy one.  This is a car that the city
issues to the Fire Chief.  At the time this was [Teresa Deloach
Reed](https://localwiki.org/oakland/Teresa_Deloach_Reed).

```{python}
fire_chief = lprs[lprs['Plate'] == '1328354']
fire_chief
```

Let's have a look at where the ALPR saw her car.

You may remember from the [plate cleaning](clean_plates.Rmd) that we've coded:

* Weekday daytime reads as *blue*;
* Weekday evening reads as *red*;
* Weekend reads as *green*;

```{python}
# Location of the Oakland City Hall from Google Maps.
OAK_CITY_HALL_COORDS = (37.805498393033204, -122.2725551318817)

oak_map = folium.Map(location=OAK_CITY_HALL_COORDS,
                     tiles='OpenStreetMap',
                     zoom_start=12)

# Drop markers where ALPR saw the Fire Chief
for i, row in fire_chief.iterrows():
    folium.Marker(
        [row['Latitude'], row['Longitude']],
        popup=row['Timestamp'],
        # Color-code the marker.
        icon=folium.Icon(color=row['Color'], icon='car', prefix='fa')
    ).add_to(oak_map)

# Mark the City Hall
folium.Marker(OAK_CITY_HALL_COORDS,
              popup='City Hall',
              icon=folium.Icon(color='lightgray', icon='info-sign')
             ).add_to(oak_map)

oak_map
```


We can see a *blue* cluster in downtown Oakland, where the Fire
Chief's car was seen on weekdays during business hours.  I bet
we've found her office.  As you can see from the 'City Hall'
marker, those are mostly clustered right near City Hall.  Also,
her car was seen twice in northern Oakland on weekday evenings
(*red*). One can only speculate what that indicates.  Maybe
dinner with a friend?  Or running errands?  Off to the scene of
a fire?  Who knows.  And then the car has been seen once more,
late at night on a weekend (*green*), in a residential area in
the hills. Her home address, maybe?


## Searching for someone


Let's look at another plate trawled from the data set.

```{python}
someone = lprs[lprs['Plate'] == '6UZA652']
someone
```

```{python}
oak_map = folium.Map(location=OAK_CITY_HALL_COORDS,
                     tiles='OpenStreetMap',
                     zoom_start=12)
for i, row in someone.iterrows():
    folium.Marker(
        [row['Latitude'], row['Longitude']],
        popup=row['Timestamp'],
        icon=folium.Icon(color=row['Color'], icon='car', prefix='fa')
    ).add_to(oak_map)
oak_map
```

What can we learn from this map?  First, it's pretty easy to
guess where this person lives: 16th and International, or
pretty near there.  And then we can see them spending some
nights and a weekend near Laney College.  Did they have an
apartment there briefly?  A relationship with someone who lived
there?


## So ... who should see these data?


* Who should have access to these data?
* Is there anything we can do to make these data less dangerous
  in terms of privacy, while maintaining their use for
  monitoring police surveillance?


## Notes

* [Electronic Frontier Foundation
  discussion](https://www.eff.org/deeplinks/2015/01/what-we-learned-oakland-raw-alpr-data)
* <https://www.eastbaytimes.com/2021/09/04/oakland-police-give-fbi-unfettered-access-to-license-plate-reader-data-according-to-lawsuit>
* <https://oaklandside.org/2021/02/08/oaklands-privacy-commission-wants-police-license-plate-surveillance-canceled/>
* <https://arstechnica.com/tech-policy/2015/03/we-know-where-youve-been-ars-acquires-4-6m-license-plate-scans-from-the-cops>
* <https://www.nbcsandiego.com/news/local/license-plate-surveillance-prompts-new-concerns-about-your-privacy/48722/>
