---
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.10.3
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Cleaning the automatic license plate reader data

```{python}
# Listing files and other utilities.
import os
# Converting strings to timestamp values.
from datetime import datetime
# Getting filenames with wildcards like "*"
from glob import glob

# Data frame library.
import pandas as pd
```

## Data collection


First, we'll gather the data.  It turns out the data is publicly available on
the Oakland public records site.

I've downloaded all the files I could find at the [Oaklandca.gov data
website](https://data.oaklandca.gov/) with [the search "license
plate"](https://data.oaklandca.gov/browse?q=license%20plate). I
found 15 files, but two contained data that were already
available in other files. The remaining 13 files are in the
`./downloads` directory.

```{python}
# Get the filenames of the downloaded CSV files.
csv_fnames = glob('downloads/*.csv')
csv_fnames
```

We load all the CSV files as Pandas data frames.

```{python}
all_data_frames = []
for csv_fname in csv_fnames:
    df = pd.read_csv(csv_fname)
    all_data_frames.append(df)
```

Notice the slight differences in the column names and the different number of columns in the loaded data frames.

```{python}
for df in all_data_frames:
    print('Column names:', ', '.join(list(df)))
```

We need to do some cleanup.  One data frame has a lower case column name `red_vrm`, where the rest have capitalized names.  Some data frames have extra columns we are not interested in.

```{python}
# Clean up columns from the loaded data frames.
fixed_data_frames = []
desired_columns = ['red_vrm', 'red_timestamp', 'location 1']
for df in all_data_frames:
    # Set all column names to be lower case.
    df.columns = [col.lower() for col in df]
    # Select only the columns of interest
    fixed_data_frames.append(df[desired_columns])
```

Now the data frames are clean, concatenate them into one data
frame, and drop any duplicate rows.

```{python}
lprs = pd.concat(fixed_data_frames)
lprs = lprs.drop_duplicates()
lprs.head()
```

The "location 1" column is text:

```{python}
lprs['location 1'].iloc[0]
```

In order to use these data on maps, we need to convert the text
here into two columns, each having floating point values, one
for "Longitude" and the other for "Latitude".

```{python}
# Drop the parentheses around the strings.
no_parens = lprs['location 1'].str[1:-1]
# Split the strings into two columns, convert to floating point.
lat_lon = no_parens.str.split(',', expand=True).astype(float)
# Rename columns
lat_lon.columns = ['Latitude', 'Longitude']
lat_lon.head()
```

Stack these columns together into a single data frame:

```{python}
all_lprs = pd.concat([lprs[['red_vrm', 'red_timestamp']], lat_lon], axis=1)
all_lprs.head()
```
Rename the first two columns:

```{python}
all_lprs = all_lprs.rename(columns={
    'red_vrm': 'Plate',
    'red_timestamp': 'Timestamp'})
all_lprs.head()
```

We will later want to distinguish between license plate reads
that are seen during the daytime (on a weekday), vs the evening
(on a weekday), vs on a weekend.  So we'll color-code the
markers. To do this, we'll write some Python code to analyze
the 'Timestamp' and choose an appropriate color.

```{python}
def get_color(ts):
    t = datetime.strptime(ts, '%m/%d/%Y %I:%M:%S %p')
    if t.weekday() >= 6:
        return 'green' # Weekend
    elif t.hour >= 6 and t.hour <= 17:
        return 'blue' # Weekday daytime
    else:
        return 'red' # Weekday evening


# Apply the function to the Timestamp column, make new column.
all_lprs['Color'] = all_lprs['Timestamp'].apply(get_color)
all_lprs.head()
```

Save to disk:

```{python}
# Save without our uninformative row labels.
# Compress to save space.
all_lprs.to_csv('all_lprs.csv.gz', index=None)
```

Now see [analyzing the plates](oakland_plates.Rmd).
